### PR TITLE
Call me Email

### PR DESCRIPTION
**Pull request by pallenSL**
Email.sln, Email\Email.fsproj

### CODE REVIEW

**Comment by jebbinSCL** [comment]
Looks like your local copy of email integration was too old? Needs a rebase before merge.

**Comment by jebbinSCL** [comment]
Will you also rename the Repo?

**Comment by jebbinSCL** [comment]
Need to change the assembly title in assemblyInfo.fs. As well as the namespace

**Comment by jebbinSCL** [comment]
Namespace, AssemblyName and Name within Imap.fsproj (Now email.fsproj) need to be changed.

**Comment by pallenSL** [comment]
Thanks.  Revisiting.
And, yes, I plan to rename the Repo too.

**Pull request closed without merging**
