### PR TITLE
Complete missed commit

### PR DESCRIPTION
**Pull request by jebbinSCL**
Credentials have already been revoked

### CODE REVIEW

**Comment by pallenSL** [comment]
I don't like the "UNSET" tests, but more importantly I'm getting an exception:
Additional information: Unrecognized attribute 'file'. Note that attribute names are case-sensitive.

Is the app.Config link format correct?

**Comment by jebbinSCL** [comment]
It should be, its the same as what I have used on the trello sync project. Do you have any suggestions to replace the unset? I just wanted something that would make it clear that you need to do something. I've added a comment to point you in the right direction as well.

**Comment by pallenSL** [comment]
Mea culpa on the syntax.

For "UNSET" it would be cleaner to check for null than to make up a new magic string meaning null, which is what we are doing.  The best I can write in my kindergarden F# is:

    let email = ConfigurationManager.AppSettings.Get("EmailAccount")
    let password = ConfigurationManager.AppSettings.Item("Password")
    
    if email |> isNull || password |> isNull then
        failwith missingCredentialsMessage

    let creds = { Email = email; Password = password }
    creds

**Comment by jebbinSCL** [comment]
I've updated it to use String.IsNullOrWhitespace, that way I can leave the setting keys in the config as blanks. Is that good?

**Comment by pallenSL** [comment]
IsNullOrWhitespace is a good call.
:shipit:

**Pull request merged**
